export const auth = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
};

export const dashboard = {
  TARGET_CREATE_SUCCESS: "TARGET_CREATE_SUCCESS",
  TARGET_CREATE_FAIL: "TARGET_CREATE_FAIL",
  GET_STATS_SUCCESS: "GET_STATS_SUCCESS",
  GET_TARGETS: "GET_TARGETS",
  SET_SEARCH_QUERY: "SET_SEARCH_QUERY",
  TARGET_QUERY_SUCCESS: "TARGET_QUERY_SUCCESS",
  TARGET_QUERY_FAIL: "TARGET_QUERY_FAIL",
};
