export const auth = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
};

export const dashboard = {
  GET_STATS_SUCCESS: "GET_STATS_SUCCESS",
  GET_STATS_FAIL: "GET_STATS_FAIL",
  GET_SECTORS_SUCESS: "GET_SECTORS_SUCESS",
  GET_COUNTRIES_SUCCESS: "GET_COUNTRIES_SUCCESS",
};

export const asr = {
  TARGET_CREATE_FAIL: "TARGET_CREATE_FAIL",
  GET_TARGETS_SUCCESS: "GET_TARGETS_SUCCESS",
  SEARCH_QUERY: "SEARCH_QUERY",
  TARGET_QUERY_SUCCESS: "TARGET_QUERY_SUCCESS",
  TARGET_QUERY_FAIL: "TARGET_QUERY_FAIL",
  RESET_QUERY: "RESET_QUERY",
};

export const target = {
  TARGET_CREATE_SUCCESS: "TARGET_CREATE_SUCCESS",
  FETCH_GEO_SUCESS: "FETCH_GEO_SUCESS",
  SET_GEO_SUCESS: "SET_GEO_SUCESS",
  INITIAL_GET_SUCCESS: "INITIAL_GET_SUCCESS",
  GET_TARGETS_DETAILS_SUCCESS: "GET_TARGETS_DETAILS_SUCCESS",
  RESET_FORM: "RESET_FORM",
};

export const error = {
  ERROR_MESSAGE: "ERROR_MESSAGE",
  RESET_ERRORS: "RESET_ERRORS",
};
